use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn copy_dir(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let s = entry.path();
        let d = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir(&s, &d)?;
        } else {
            if let Some(parent) = d.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(&s, &d)?;
        }
    }
    Ok(())
}

fn collect_files(dir: &Path, acc: &mut Vec<PathBuf>) -> std::io::Result<()> {
    for e in fs::read_dir(dir)? {
        let e = e?;
        let p = e.path();
        if p.is_dir() {
            collect_files(&p, acc)?;
        } else if p.is_file() {
            acc.push(p);
        }
    }
    Ok(())
}

fn write_bundled_rs(out_dir: &Path, mirror: &Path, bundled: bool) -> std::io::Result<()> {
    let path = out_dir.join("scewin_bundled.rs");
    let mut w = fs::File::create(&path)?;

    writeln!(w, "// @generated by build.rs")?;
    writeln!(w, "use ::std::io;")?;
    writeln!(w, "use ::std::path::Path;")?;
    writeln!(w)?;

    if !bundled {
        writeln!(w, "pub const BUNDLED: bool = false;")?;
        writeln!(w)?;
        writeln!(
            w,
            "pub fn extract_embedded(_dest_base: &Path) -> io::Result<()> {{ Ok(()) }}"
        )?;
        return Ok(());
    }

    writeln!(w, "pub const BUNDLED: bool = true;")?;
    writeln!(w)?;
    writeln!(w, "pub fn extract_embedded(dest_base: &Path) -> io::Result<()> {{")?;

    let mut files = Vec::new();
    collect_files(mirror, &mut files)?;
    files.sort();

    for f in files {
        let rel = f.strip_prefix(mirror).unwrap();
        let rel_slash = rel.to_string_lossy().replace('\\', "/");
        // join() path in generated code — only [A-Za-z0-9._/] from our tree
        writeln!(w, "    {{")?;
        writeln!(
            w,
            r#"        const BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/scewin_mirror/{rel}"));"#,
            rel = rel_slash
        )?;
        writeln!(
            w,
            r#"        let out_path = dest_base.join("{rel}");"#,
            rel = rel_slash
        )?;
        writeln!(w, "        if let Some(parent) = out_path.parent() {{")?;
        writeln!(w, "            ::std::fs::create_dir_all(parent)?;")?;
        writeln!(w, "        }}")?;
        writeln!(w, "        ::std::fs::write(out_path, BYTES)?;")?;
        writeln!(w, "    }}")?;
    }

    writeln!(w, "    Ok(())")?;
    writeln!(w, "}}")?;
    Ok(())
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let profile = std::env::var("PROFILE").unwrap();
    let target = manifest.join("target").join(&profile);
    let src = manifest.join("SCEWIN");
    let dst_target = target.join("SCEWIN");
    let mirror = out_dir.join("scewin_mirror");

    println!("cargo:rerun-if-changed=SCEWIN");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/icon/nvram.ico");

    #[cfg(windows)]
    {
        let icon_path = manifest.join("src").join("icon").join("nvram.ico");
        if icon_path.is_file() {
            let mut res = winresource::WindowsResource::new();
            res.set_icon(icon_path.to_string_lossy().as_ref());
            if let Err(e) = res.compile() {
                println!("cargo:warning=failed to compile Windows icon resource: {e}");
            }
        } else {
            println!(
                "cargo:warning=no icon found at {} (add src/icon/nvram.ico to embed an exe icon)",
                icon_path.display()
            );
        }
    }

    let bundled = src.is_dir();
    if bundled {
        let _ = fs::remove_dir_all(&mirror);
        if let Err(e) = copy_dir(&src, &mirror) {
            eprintln!("cargo:warning=failed to mirror SCEWIN to OUT_DIR: {e}");
        }
    } else {
        let _ = fs::remove_dir_all(&mirror);
    }

    let embed_ok = mirror.is_dir() && fs::read_dir(&mirror).map(|mut d| d.next().is_some()).unwrap_or(false);
    if let Err(e) = write_bundled_rs(&out_dir, &mirror, embed_ok) {
        eprintln!("cargo:warning=failed to write scewin_bundled.rs: {e}");
    }

    // Copy beside target exe (dev convenience)
    if src.is_dir() {
        let _ = fs::remove_dir_all(&dst_target);
        if let Err(e) = copy_dir(&src, &dst_target) {
            println!(
                "cargo:warning=failed to copy SCEWIN to {}: {e}",
                dst_target.display()
            );
        }
    } else {
        println!(
            "cargo:warning=no SCEWIN/ at {} — build without embedded SCEWIN; ship SCEWIN next to the exe or add the folder to embed it",
            manifest.display()
        );
    }
}
